image: tetraweb/php:7.0

stages:
  - deploy

deploy_production:
  stage: deploy
  script:
    - ssh ec2-user@topweatherroofing.tk "
      cd /var/www/topweatherroofing &&
      git checkout . &&
      git checkout master &&
      git pull"
  only:
    - master