image: tetraweb/php:7.0

#services:
#  - mysql

#variables:
#  MYSQL_DATABASE: topweatherroofing
#  MYSQL_ROOT_PASSWORD: root
#  DB_HOST: mysql
#  DB_USERNAME: user

stages:
#  - test
  - deploy

before_script:
  - mkdir -p ~/.ssh
  - echo -e "$DEPLOY_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

#unit_test:
#  stage: test
#  script:
#    - cp .env.example .env
#    - composer install
#    - php artisan key:generate
#    - php artisan migrate
#    - vendor/bin/phpunit

deploy_production:
  stage: deploy
  script:
    - ssh ec2-user@topweatherroofing.tk "
      cd /var/www/html/topweatherroofing &&
      git checkout . &&
      git checkout master &&
      git pull"
  only:
    - master