image: hitalos/laravel:latest

stages:
  - deploy

deploy_production:
  stage: deploy
  script:
    - 'sshpass -V'
    - 'export SSHPASS=$USER_PASS'
    - 'sshpass -e scp -o stricthostkeychecking=no -r . ec2-user@topweatherroofing.tk:/var/www/html  environment: production'
    - ''
  only:
    - master